security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      form_login:
        login_path: login
        check_path: login
      logout:
        path: logout
        target: /    
      lazy: true
      provider: app_user_provider
      custom_authenticator: App\Security\UserAuthenticator
      entry_point: 'App\Security\UserAuthenticator'
  access_control:
    - { path: ^/user, roles: IS_AUTHENTICATED }
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/user, roles: ROLE_USER }
  role_hierarchy:
      ROLE_ADMIN: [ROLE_USER]
when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4 # Lowest possible value for bcrypt
        time_cost: 3 # Lowest possible value for argon
        memory_cost: 10 # Lowest possible value for argon
