controllers:
    resource: ../src/Controller/
    type: attribute

home:
  path: "/"
  controller: App\Controller\HomeController::homeIndex

checkout:
    path: /checkout
    controller: App\Controller\CheckoutController::checkout

# Gestion de compte

register:
  path: "/register"
  controller: App\Controller\RegistrationController::register

login:
  path: "/login"
  controller: App\Controller\SecurityController::login

logout:
  path: "/logout"
  controller: App\Controller\SecurityController::logout

contact:
  path: "/contact"
  controller: App\Controller\HomeController::contact

profile:
  path: "/profile"
  controller: App\Controller\UserController::profile

profileEdit:
  path: "/profile_edit"
  controller: App\Controller\UserController::editProfile
  
adminUsers:
  path: "/admin_users"
  controller: App\Controller\UserController::listUsers

# Product

productDescription:
  path: "/{id}/productDescription"
  controller: App\Controller\ProductController::productDescription

addProduct:
  path: "/product_new"
  controller: App\Controller\ProductController::new

productEdit:
  path: "/product_edit"
  controller: App\Controller\ProductController::edit

productDelete:
  path: "/product_delete"
  controller: App\Controller\ProductController::delete

like_product:
    path: '/like_product/{id}'
    controller: 'App\Controller\ProductController::likeProduct'
    methods: ['POST']

unlike_product:
    path: '/unlike_product/{id}'
    controller: 'App\Controller\ProductController::unlikeProduct'
    methods: ['POST']

most_liked_products:
    path: '/most_liked_products'
    controller: 'App\Controller\HomeController::mostLikedProducts'
    methods: ['POST']

products_with_promotion:
    path: '/products_with_promotion'
    controller: 'App\Controller\HomeController::productsWithPromotion'
    methods: ['POST']
    
# Cart

panier:
  path: "/panier"
  controller: App\Controller\CartController::panier

add_to_cart:
    path: '/add_to_cart/{productId}'
    controller: 'App\Controller\CartController::addToCart'

remove_from_cart:
  path: '/remove_from_cart/{cartId}'
  controller: 'App\Controller\CartController::removeFromCart'

# Bar de recherche

search:
  path: "/search"
  controller: App\Controller\HomeController::search
