controllers:
    resource: ../src/Controller/
    type: attribute

home:
  path: "/"
  controller: App\Controller\HomeController::homeIndex

checkout:
    path: /checkout
    controller: App\Controller\CheckoutController::checkout
    methods: ['GET']

# Compte User

register:
  path: "/register"
  controller: App\Controller\RegistrationController::register

login:
  path: "/login"
  controller: App\Controller\SecurityController::login

logout:
  path: "/logout"
  controller: App\Controller\SecurityController::logout

contact:
  path: "/contact"
  controller: App\Controller\HomeController::contact

profile:
  path: "/profile"
  controller: App\Controller\UserController::profile

profileEdit:
  path: "/profile_edit"
  controller: App\Controller\UserController::editProfile
  
# Produit

productDescription:
  path: "/{id}/productDescription"
  controller: App\Controller\ProductController::productDescription

addProduct:
  path: "/product_new"
  controller: App\Controller\ProductController::new

productEdit:
  path: "/product_edit"
  controller: App\Controller\ProductController::edit

productDelete:
  path: "/product_delete"
  controller: App\Controller\ProductController::delete

# Promotion

promotion:
  path: "/promotion"
  controller: App\Controller\PromotionController::listPromotions

addPromotion:
  path: "/addPromotion"
  controller: App\Controller\PromotionController::addPromotion

deletePromotion:
  path: "/{id}/deletePromotion"
  controller: App\Controller\PromotionController::deletePromotion

editPromotion:
  path: "/{id}/editPromotion"
  controller: App\Controller\PromotionController::editPromotion

# Panier

panier:
  path: "/panier"
  controller: App\Controller\CartController::panier

add_to_cart:
    path: '/add_to_cart/{productId}'
    controller: 'App\Controller\CartController::addToCart'

removeFromCart:
  path: "/remove_from_cart"
  controller: App\Controller\CartController::removeFromCart


# Promotion_Product



# Bar de recherche

search:
  path: "/search"
  controller: App\Controller\HomeController::search

filter_products:
    path: '/home/index'
    controller: App\Controller\ProductController::filterProducts