controllers:
    resource: ../src/Controller/
    type: attribute

home:
  path: "/"
  controller: App\Controller\HomeController::homeIndex

register:
  path: "/register"
  controller: App\Controller\RegistrationController::register

login:
  path: "/login"
  controller: App\Controller\SecurityController::login

logout:
  path: "/logout"
  controller: App\Controller\SecurityController::logout

contact:
  path: "/contact"
  controller: App\Controller\HomeController::contact

panier:
  path: "/panier"
  controller: App\Controller\HomeController::panier

product:
  path: "/{id}/productDescription"
  controller: App\Controller\ProductController::productDescription

addProduct:
  path: "/product_new"
  controller: App\Controller\ProductController::new

productEdit:
  path: "/product_edit"
  controller: App\Controller\ProductController::edit

productDelete:
  path: "/product_delete"
  controller: App\Controller\ProductController::delete

# delete_form:
#   path: "/delete_form"
#   controller: App\Controller\ProductController::deleteForm

addToCart:
  path: "/add_to_cart/{productId}"
  controller: App\Controller\CartController::addToCart

removeFromCart:
  path: "/remove_from_cart"
  controller: App\Controller\CartController::removeFromCart

search:
  path: "/search"
  controller: App\Controller\ProductController::search