controllers:
    resource: ../src/Controller/
    type: attribute

home:
  path: "/"
  controller: App\Controller\HomeController::homeIndex

register:
  path: "/register"
  controller: App\Controller\RegistrationController::register

login:
  path: "/login"
  controller: App\Controller\SecurityController::login

logout:
  path: "/logout"
  controller: App\Controller\SecurityController::logout

contact:
  path: "/contact"
  controller: App\Controller\HomeController::contact

product:
  path: "/{id}/productDescription"
  controller: App\Controller\ProductController::productDescription

search:
  path: "/partials/_header.html.twig"
  controller: App\Controller\ProductController::search

panier:
  path: "/panier"
  controller: App\Controller\HomeController::panier

addProduct:
  path: "/product_new"
  controller: App\Controller\ProductController::new

productEdit:
  path: "/product_edit"
  controller: App\Controller\ProductController::edit

productDelete:
  path: "/product_delete"
  controller: App\Controller\ProductController::delete

delete_form:
  path: "delete_form"
  controller: App\Controller\ProductController::deleteForm

add_to_favorite:
  path: "add_to_favorite"
  controller: App\Controller\FavoriteController::addToFavorite